---
abstract: 'Device and library agnostic color spaces.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Number::Delta: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Color
no_index:
  directory:
    - inc
    - t
requires:
  Color::Library: 0.02
  Moose: 0.74
  MooseX::Aliases: 0.03
  MooseX::Clone: 0.03
  MooseX::Types: 0.19
resources:
  license: http://dev.perl.org/licenses/
version: 0.26
