---
abstract: 'Device and library agnostic color spaces.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Pod::Coverage::Moose: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Graphics-Color
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.54
  MooseX::Clone: 0.03
version: 0.09
