---
abstract: 'Device and library agnostic color spaces.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Color
no_index:
  directory:
    - inc
    - t
requires:
  Color::Library: 0.02
  Moose: 0.54
  MooseX::Clone: 0.03
  MooseX::Storage: 0.14
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
